### ISSUE TITLE
XI (Northern Ireland) VAT numbers

### ISSUE THREAD

**Issue by JoryHogeveen** [NKoonen/vatchecker#14]
> As of 01/01/2021, the VoW service to validate UK (GB) VAT numbers ceased to exist while a new service to validate VAT numbers of businesses operating under the Protocol on Ireland and Northern Ireland appeared. These VAT numbers are starting with the “XI” prefix, which may be found in the “Member State / Northern Ireland” drop down under the new entry “XI-Northern Ireland”. Moreover, any quote of “Member State” is replaced by “Member State / Northern Ireland” and any quote of “MS” is replaced by “MS / XI”. All traders seeking to validate UK (GB) VAT numbers may address their request to the UK Tax Administration.

Find out if this is required for the plugin or not.

**Comment by HartLarsson** [comment]
EU directive n. 2020/1756 del 20 novembre 2020 specify that the North Ireland will have a bew XIU identification code instaed of GB and will be managed as a EU state so Taxes must be applied when is aprivate or not VIES validated VAT code
