### ISSUE TITLE
VAT Check doesnt work when switching between addresses

### ISSUE THREAD

**Issue by Johnwulp** [NKoonen/vatchecker#2]
hi!

Thanks for this great module!

I noticed that during checkout, if you fill in a correct VAT number, you will be placed into the correct group.
But, if you switch to another address that doesn't have a valid (or none) VAT number, the customer is not removed from this group.

Is that something than can be fixed?

**Comment by NKoonen** [comment]
Thanks for pointing out this issue.
This will be fixed in the next update.
