### ISSUE TITLE
Old customers

### ISSUE THREAD

**Issue by jjmontalban** [NKoonen/vatchecker#29]
Thanks for your module and we use and works perfect for new customer whern are registered with VAT.

But since 1.6 version we have some customers with valid VAT using old native module for that. And when old customers order now in our new version (1.7.8.6) orders show tax again. There are any solution for old customers and remove again taxes? How can do it your module for apply this changes to our old customers?

Regards

**Comment by NKoonen** [comment]
In our module that is currently not possible. Officially you can only send VAT free for corresponding shipping address. And customers can always change or add an address, that is why it will always check when a (older) customer is placing a new order. 

example:
Customer A orders from a foreign country and the VAT module checks out, so the customers pays 0% VAT.
Customer A orders again from the same account but this time the shipping address is in the same country as your company. This means it is not intracommunautaire delivery and Customer A has to pay VAT.

**Comment by jjmontalban** [comment]
First of all thanks for answering.

So I understand that old customers who have a valid VAT at an old address should still have a 0% tax.

But we have detected problems in some of our clients who, even having a valid VAT at a out of Spain address, must to pay with taxes.

This problem occurs only on some old cutomers. Then I understand that it is a specific problem of specific clients. may be problem is for migration data. Other old customers have not had this problem.

Is it possible to modify any data in any table in the database for these cases so that they can buy again without fees?

Best regards
