### ISSUE TITLE
remove the use of override using a solution similar to vatnumber module

### ISSUE THREAD

**Issue by maofree** [NKoonen/vatchecker#31]
Hi
is it possible to remove the override solution using the same solution of vatnumber module?
with the hook actionTaxManager and extends TaxManagerModule instead of extends Module?

https://github.com/PrestaShop/vatnumber

now I've seen another module that use the same solution of vatnumber

thanks

**Comment by NKoonen** [comment]
I'm sorry this a specific use case. You can always merge these two overrides for your project.
For now this is not planned.
