### ISSUE TITLE
isEUCountry function always return false on PrestaShop 8.x

### ISSUE THREAD

**Issue by Caleydon** [NKoonen/vatchecker#36]
Hi. I've tested module on PrestaShop 8.1.2 and it doesn't working correctly. I discovered that **isEUCountry** function always return **false** so then always **valid = null**.

Could you please check what is wrong with isEUCountry function on PrestaShop 8.x ?

**Comment by NKoonen** [comment]
> Hi. I've tested module on PrestaShop 8.1.2 and it doesn't working correctly. I discovered that **isEUCountry** function always return **false** so then always **valid = null**.
> 
> Could you please check what is wrong with isEUCountry function on PrestaShop 8.x ?

I already feared something like this, since we currently do i direct query into the database.
(because PS does not offer proper functions for getting countries in Multistore mode)

Just changed it back to before. Please let me know if this resolves your issue.

**Comment by Caleydon** [comment]
Thank you. But it still doesn't working.
