### ISSUE TITLE
BUG in Debug

### ISSUE THREAD

**Issue by HartLarsson** [NKoonen/vatchecker#4]
![image](https://user-images.githubusercontent.com/16102074/101182893-03437180-364f-11eb-9d51-8dee8dd22773.png)

PS 1.7.6.9
PHP 7.2

**Comment by NKoonen** [comment]
I think you mean PHP7.2, and not 2.7.
Please ask your hosting provider to enable/install SoapClient on your PHP version.

**Comment by HartLarsson** [comment]
> I think you mean PHP7.2, and not 2.7.
> Please ask your hosting provider to enable/install SoapClient on your PHP version.

sorry was a typo 👍
