### ISSUE TITLE
Different Country shipping address vs Registered VAT No Country

### ISSUE THREAD

**Issue by Fleckmyus** [NKoonen/vatchecker#40]
The current edition, compared to the old edition, allows delivery to another country than the billing address.
It is not normal that the customer can select a different delivery address other than the selected VAT number Country from the billing address and still have VAT deducted. For instance a customer with the valid VAT number registered in France can select a shipping address in Spain and the VAT is deducted.

**Comment by NKoonen** [comment]
We only check the VAT if it's not the same as the country of origin (set in the module settings).
So according to the intra-community supply law you can only send it tax free if it is not in the same country as you send it from. The module provides a extra option to automatically put VAT validated customers into a specific customer group. But this customer group does NOT have any extra logics attached. The extra customer group selection is hereby only for your own administration

**Comment by NKoonen** [comment]
According to the intra-community supply law, the shipping address is leading. This means if you have a valid VAT number for the shipping address but the invoice address is in your country of origin it's still correct to deliver tax free.

This goes both ways, if you have a company abroad, but the shipping address is in the country of origin you can not deliver without tax.

(if you do not agree, please refer to some links for documentation)

**Comment by Fleckmyus** [comment]
OK, great. Thank you for your fast answer.
