### ISSUE TITLE
When the VAT number is valid the VAT rate should be 0% and not be disabled.

### ISSUE THREAD

**Issue by Steven44223** [NKoonen/vatchecker#41]
When the VAT/TAX is set to disabled/false the invoice shows nothing in the VAT Rate. This should be set to 0%.

When set to 0% the invoice shows a VAT rate of 0% and the VAT Detail is shown with the text No VAT.

This makes it more clear that it is an european intra-Community transaction.

TaxRulesTaxManager.php:
```
- $tax_enabled = false;
+ $tax = new Tax();
+ $tax->rate = 0;
+ return new TaxCalculator([$tax]);
```
VAT/TAX DISABLED:
![VAT-DISABLED](https://github.com/NKoonen/vatchecker/assets/75079800/5ec50863-b508-465d-bc44-613b08639f5a)

VAT/TAX 0%
![VAT-0](https://github.com/NKoonen/vatchecker/assets/75079800/09854959-eb76-428b-b3d0-a2fcd6cd9cfc)

**Comment by NKoonen** [comment]
This is actually generated by Prestashop. We currently don't make any edits in the invoice pdf.
You could edit this translation "Frontoffice > your theme > Shop > pdf".
Or you could edit/override the default template.

**Comment by Steven44223** [comment]
Hi,

Yes I know, I didn't make any changes to the PDF's.

When you set the tax to 0 (TaxRulesTaxManager.php) PrestaShop adds a new entry in the ps_order_detail_tax table This will show the 0% VAT Rate en VAT Detail table in the pdf invoice.

If you disable tax (current code), PrestaShop does not add a new entry in the ps_order_detail_tax table and the VAT Rate will show as blank and the VAT Detail table in the invoice pdf does not show.

**Comment by NKoonen** [comment]
So instead of setting tax to 0% in the module, you'd like the module to create a 0% tax rule and use this for the orders.
Makes sense! Might be a good update. (will make this when i have time)

**Comment by Steven44223** [comment]
Yes, I think it's more clear for the customer. The changes to the code in my first post is working for me.
