### ISSUE TITLE
Products on discount - incorrect calculation netto price

### ISSUE THREAD

**Issue by futurowebpl** [NKoonen/vatchecker#42]
We noticed an error in the operation of the module - when converting the VAT rate, it does not take into account the price after the discount, but calculates it from the base price (before the discount).

The correct conversion should look like this:
Price after discount - 1587 Lei
VAT rate - 19%
Price excluding VAT - 1,333.61 Lei

The module calculates as follows:
Price before discount - 1987 Lei
VAT rate - 19%
Price before discount excluding VAT - 1669.75 Lei

from this amount, the module subtracts the gross value of the discount - 400 Lei
Net price calculated by the module - 1269.75 Lei
Therefore, the net price is lower by 63.86 Lei

**Comment by NKoonen** [comment]
The module disables the tax rule for customers with 0% vat. 
It could depend on wether your discount is with or without tax.

So could you share with me how / where you have set the discount?

**Comment by futurowebpl** [comment]
![obraz](https://github.com/NKoonen/vatchecker/assets/43948137/c80d6583-1e76-47fd-9709-b593277abafe)

**Comment by futurowebpl** [comment]
Okay,

If in this field we enter netto price - everythings works good,

so - I close this task.
