### ISSUE TITLE
No Northern Ireland on list

### ISSUE THREAD

**Issue by maciekwyka** [NKoonen/vatchecker#43]
In configuration should be Northern Ireland (XI) to enable
<img width="377" alt="Zrzut ekranu 2024-03-15 o 16 01 41" src="https://github.com/NKoonen/vatchecker/assets/12991339/b4cbcd26-1d87-4bc3-9bdd-af6348c0394f">

**Comment by NKoonen** [comment]
That is correct, but Prestashop does not have North Ireland as a country by default.
You would have to manually create North Ireland as a country in Prestashop's backoffice at: "international > Locations > Countries" and make sure the iso code is "XI". If you have done this, it will show up in the module.
