### ISSUE TITLE
Prestashop 8 compatibility

### ISSUE THREAD

**Issue by felixd** [NKoonen/vatchecker#44]
I am not able to install module on Prestashop 8.1.x (8.1.5 exactly).

**Comment by NKoonen** [comment]
Can you elaborate? Can you share the error you are getting?

**Comment by felixd** [comment]
No more errors. 

I have downloaded ZIP of this repo and I am trying to install it as a module. 
Maybe that's what I am doing wrong. 

![image](https://github.com/NKoonen/vatchecker/assets/4963164/b1202132-02e0-4d89-9a37-9f08fd43ef2b)

**Comment by NKoonen** [comment]
To install the plugin directly from the Github zip you would have to do a couple of steps.

1. Download the plugin (zip file)
2. Extract the module on your computer locally
3. Rename the folder from "vatchecker-master" TO "vatchecker"
4. Right click the "vatchecker" folder and rezip it (make a zip file from it)
5. Use the newly created zip file.

As an alternative you could download it [here](https://www.prestashop.com/forums/topic/1066616-free-module-vat-checker/#comment-3483105).

**Comment by felixd** [comment]
Thank You for your update. I have merged Your instructions with README.md file and also I have corrected some descriptions of Your module together with full pl_PL transation. 

Keep the good work!
