### ISSUE TITLE
Problem with function isEUCountry( $countryCode )

### ISSUE THREAD

**Issue by felixd** [NKoonen/vatchecker#47]
`$countryId` variable returned by `Tools::getValue` is `string` type:

var_dump in Prestashop 8.1.5
```log
# Poland -> "14"
string(2) "14"
```
https://github.com/NKoonen/vatchecker/blob/1309d1c0509b2c3434c5261771a09e4a95e98f0f/ajax.php#L16-L18

`isEUCountry` funcation compares variables using  `===`  (identical, checks also type)

https://github.com/NKoonen/vatchecker/blob/1309d1c0509b2c3434c5261771a09e4a95e98f0f/vatchecker.php#L944-L954

I have created quickfix pull request for this #46

Prestashop version: 8.1.5

**Comment by NKoonen** [comment]
Thanks, good catch!  :)
