### ISSUE TITLE
Override method should be change 

### ISSUE THREAD

**Issue by Triloworld** [NKoonen/vatchecker#48]
Hello,
Module is great. We like to help support as we need update old module to this one. Right now your module is best candidate but there is used override pattern that isn't recommended

Recommended pattern to work with PayPal is from example module - https://github.com/202ecommerce/paypal/issues/150
Prestashop have hooks that is used to evaluated Tax.

There is need to have composer, hook and Github Action to generate zip package. This will help new adoption

**Comment by NKoonen** [comment]
Sounds good, you can make a pull request.

**Comment by NKoonen** [comment]
I think this issue is resolved with the latest version, right?
